# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: clarenceee
email: zhouzhouatchina@msn.cn
description: > # this means to ignore newlines until "baseurl:"
sitedescription: >
    Powered by <a href="http://jekyllrb.com" target="_black"> Jekyll </a>
    , hosted on <a href="https://pages.github.com/" target="_black"> Github Pages </a> and
    inspired by<a href="http://marcgg.com/" target="_black"> marcgg </a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elbow95.github.io"
github_username: elbow95
permalink: /blog/:title.html
port: 5001
# Build settings
markdown: kramdown
