# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chen's blog
email: zhouzhouatchina@msn.cn
description: > # this means to ignore newlines until "baseurl:"
sitedescription: >
  Personal Blog powered by <a href="http://jekyllrb.com">Jekyll</a> and hosted on <a href="https://github.com">Github</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.elbow95.me"
github_username: elbow95

# Build settings
markdown: kramdown
